# -*- coding: utf-8 -*-
"""Data_Loader_explorer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1New9M5d2pEnsyMAsD9UdGz96Fg5eHTMU
"""

#libraries
!pip install pyfastx
!pip3 install numpy 
!pip install biopython
!pip install h5py
!pip install kPAL
!pip install khmer

#modules
import pyfastx
import numpy as np

from google.colab import files
uploaded = files.upload()

for name, seq in pyfastx.Fasta('GCF_000008865.2_ASM886v2_genomic.fa', build_index = False):
  print (name,seq)

c = 1
for name, seq in pyfastx.Fasta('GCF_000008865.2_ASM886v2_genomic.fa', build_index = False):
  print (c, len(seq), seq) 
  c = c+1

fa = pyfastx.Fasta('GCF_000008865.2_ASM886v2_genomic.fa')
print (type(fa), fa.size)
for i in range(len(fa)):
  print (type(fa[i]), len(fa[i]))

seq = fa[0]
c= 1
print (len(seq))
for s in seq: 
  print (c,len(s),s)
  c = c +1
  if c > 50:
    break